

FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Set working directory (same as Laravel app)
WORKDIR /var/www/html

EXPOSE 80
